### PR TITLE
Include link to upgrade guide in readme

### PR DESCRIPTION
**Pull request by tlshaheen**
I had to dig through the discussion in #382 before I found a link to @SammyK 's site where I was able to find the upgrade guide for v4.x to v5.x.

This pull request puts a link to the upgrade guide up-front in the Readme!

### CODE REVIEW

**Comment by SammyK** [comment]
Aw, shucks. :) @gfosco You think we can get away with this since it's not technically "Facebook official"? :)

**Comment by tlshaheen** [comment]
@SammyK If not, can we make one that is FB offish? Obviously its several hours worth of time to convert from v4.x to v5.x, and without a guide, it would be a lot harder.

**Comment by SammyK** [comment]
@tlshaheen Thanks! :)

I'm pretty sure the link will be fine. I didn't add the link myself just because I didn't want to seem like I was spamming the codebase. :)

**Comment by gfosco** [comment]
Heck, I want to link his upgrade guide on the developers.facebook.com site (and I will, once I get around to updating it...)

**Comment by SammyK** [comment]
:+1: Totes feeling the love. :)

**Pull request merged**
