### PR TITLE
Update FacebookRedirectLoginHelper.php

### PR DESCRIPTION
**Pull request by EliuFlorez**
Change IsSet() To is_null()

### CODE REVIEW

**Comment by EliuFlorez** [comment]
@facebook-github-bot thank you! ready.

**Comment by SammyK** [comment]
Hey @EliuFlorez! Why did you make this change? It breaks the logic.

**Comment by EliuFlorez** [comment]
@SammyK $ accessToken is valid for isset but not for is_null optionally return the null value

**Comment by yguedidi** [comment]
@EliuFlorez I think you mean `!is_null()`, not `is_null()`.
But `isset()` also returns `false` when the value is `null`, even if a variable is "set".

> isset — Determine if a variable is set and is not NULL ([from the doc](http://php.net/manual/en/function.isset.php))

**Comment by EliuFlorez** [comment]
@yguedidi true it is! is_null () :(

**Comment by yguedidi** [comment]
@EliuFlorez so this can be closed, as your change already handled by `isset()` :)

**Pull request closed without merging**
