### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by stevenmaguire**
Per https://github.com/SammyK/facebook-php-sdk-v4/issues/1

### CODE REVIEW

**Comment by SammyK** [comment]
:+1:

**Comment by SammyK** [comment]
Also need to remove the test `FooSignedRequestHelperFacebookClient::testSignedRequestDataCanBeRetrievedFromGetData()`

**Comment by stevenmaguire** [comment]
Blarg! How did those tests pass after I removed the implementation!?

**Comment by SammyK** [comment]
:monkey:

**Pull request merged**
