### PR TITLE
PSR-2

### PR DESCRIPTION
**Pull request by yguedidi**
A big PR including #346, #351, #352, #353, #355

This still need some love, I just run some tools.
But right now it's too late for me, I should sleep, I'll finish it tomorrow.

### CODE REVIEW

**Comment by SammyK** [comment]
Wowzers! Great work @yguedidi! :)

**Comment by yguedidi** [comment]
Thanks @SammyK, I'll check each file tomorrow, have to sleep now :)

**Comment by yguedidi** [comment]
@gfosco I suggest some rules on top of PSR-2:

- Always write methods/functions definition in one line
- Always write a ternary in one line, if it's too long, use a proper `if`/`else`
- Never split error messages
- Extra: align PHPDoc types/var names/comments (first step to PSR-5)

@SammyK any thoughts? :)

**Comment by SammyK** [comment]
:+1: for common docblocks!

:-1: for everything else. Wrapping lines makes things much easier to read. I really don't like having to use horizontal scroll while coding. :) Plus it's [pretty standard to wrap things for readability](http://framework.zend.com/manual/1.12/en/coding-standard.coding-style.html).

**Comment by yguedidi** [comment]
@SammyK My args:
- I personally don't like multiline methods/functions signatures, I found them not much more readable. And if you want your methods/functions signature be "vertically" documented, use its DocBlock. :)
- ternary is the shortcut of a basic `if`/`else` statement. If this shortcut is too long in one line, you should consider using the `if`/`else`. A ternary on multiple line is less clear than a proper `if`/`else` IMO.
- mainly about hard-coded string (error messages, ...), I prefer to not use concatenation, for me it not makes sense, and not much more readable (and if the goal is to see the full string, most of use now have wide screens LOL)

And about standards, Symfony2 [doesn't wrap methods](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Request.php#L237) and [doesn't split hard-coded strings](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/PdoSessionHandler.php#L178).

And it has more stars on GitHub than Zend Framework (troll) :)

**Comment by SammyK** [comment]
So you're saying we'd be trying to copy Zend like this? :)

**Comment by yguedidi** [comment]
I don't understand, sorry :/

**Comment by SammyK** [comment]
It was just a bad joke. Lol :)

**Comment by yguedidi** [comment]
I know :)
So, some args against mine? Lol

**Comment by yguedidi** [comment]
@gfosco I give my args, please, as the maintainer of this repo, tell me what you accept or not for the SDK, to let me finish this pretty big PR :)

**Comment by gfosco** [comment]
I'll accept your rules on top of PSR-2, @yguedidi :)

**Comment by yguedidi** [comment]
Perfect, thanks @gfosco! I'll finish this one this week-end :)

**Comment by SammyK** [comment]
:+1: Honestly I don't care one way or another on wrapping. I just have my personal preference which I recognize is 100% subjective. :)

All I really care about is 2 things: 1) SOLID, domain-specific, testable, easy-to-understand code and 2) being a team player within the community. Outside of that... #YOLO :)

It is nice to have fine-grained standards within the project like this. I hope you'll be able to help enforce this @yguedidi! Maybe even adding a few lines to the contributing readme?

BTW you might have have to call me out on wrapping in future PR's! :) Or should I say "rapping"...

**Comment by yguedidi** [comment]
@gfosco @SammyK Updated! Please check it, I surely forgot some things :)

**Comment by yguedidi** [comment]
@stevenmaguire and @rpalladino please also check this one, thanks

**Comment by stevenmaguire** [comment]
I believe I'm good on my end. If something creeps up later, we can fix independently. This is a great body of work!

**Comment by SammyK** [comment]
It's kinda hard to read the diff on this one. Would have been better to just do it a little at a time like we had it but it's all good. :)

There's still merge conflicts.

**Comment by yguedidi** [comment]
@SammyK [Here](https://github.com/facebook/facebook-php-sdk-v4/pull/356/files?w=1) is a diff without whitespace difference ;)

Conflict resolved, they're due to the recent merged PR.

**Comment by SammyK** [comment]
Ooo! I didn't know about that "sans whitespace" diff feature! Thanks! :)

Great work! :+1: for this!

@gfosco I've got 4 more examples to add and then the doc PR will be ready! Hopefully within a few hours!

**Comment by stevenmaguire** [comment]
go ninja, go ninja, go

**Comment by rpalladino** [comment]
Looks good to me!

**Comment by yguedidi** [comment]
:clap:

**Comment by SammyK** [comment]
What!? The Facebook PHP SDK is now PSR-2 compliant!?





Nice work guys! :) ... although there are lots of warnings about lines longer than 120. Perhaps we should add a custom `ruleset.xml` for that?

CC // @philsturgeon

**Pull request merged**
