### PR TITLE
Update 4.1 docs to refer to version 5

### PR DESCRIPTION
**Pull request by SammyK**
Based on our new marketing schema. :)

### CODE REVIEW

**Comment by roman02** [comment]
@SammyK, the updated text related to this ticket says this: "Killed `FacebookSession` in favor of the `AccessToken` entity". However, the examples everywhere still prescribe using FacebookSession.

**Comment by SammyK** [comment]
@roman02 Which examples are you referring to?

**Comment by roman02** [comment]
@SammyK, for example, the home page of this project.

**Comment by SammyK** [comment]
The master branch has the [latest `README.md` for v5](https://github.com/facebook/facebook-php-sdk-v4/blob/master/README.md) that does not include `FacebookSession`.

**Comment by roman02** [comment]
Thanks. Which files need to be included if NOT using Composer?

**Comment by SammyK** [comment]
Everything in [`src/Facebook/`](https://github.com/facebook/facebook-php-sdk-v4/tree/master/src/Facebook)

**Pull request merged**
