### PR TITLE
Guzzle v6.1 compatibility

### PR DESCRIPTION
**Pull request by serhatdurum**
Guzzle v6.1 compatibility great job and many thanks for @SammyK

### CODE REVIEW

**Comment by gfosco** [comment]
Hmm.. Upping the minimum PHP version to 5.5.. thoughts @SammyK @yguedidi ?

**Comment by gfosco** [comment]
Also this has failed Travis for all versions.

**Comment by yguedidi** [comment]
I think this should be done in 6.0

**Comment by SammyK** [comment]
Def a 6.0 thing. In fact I was hoping 6.0 could be Guzzle-only and we rip out all the custom HTTP client stuff. Now that the latest version of Guzzle is PSR-7, it shouldn't be changing much going forward (or so I hear from those with some insider information). :)

Dependency on Guzzle would make PHP SDK v6.0 dependent on composer which was the big drawback a few years ago. These days we could probably get away with it since even those without composer on their servers can still install everything locally and there's other workarounds we could discuss.

**Comment by gfosco** [comment]
I'll close this for now... can be addressed when we're working towards 6.0.  Thanks!

**Comment by SammyK** [comment]
Thanks for keeping on pushing for Guzzle 6 @serhatdurum! We'll definitely get it added eventually. :)

**Pull request closed without merging**
