### PR TITLE
Bump Graph version to v2.6

### PR DESCRIPTION
**Pull request by SammyK**
[Graph v2.6](https://developers.facebook.com/docs/apps/changelog) is the new hotness. :)

### CODE REVIEW

**Comment by yguedidi** [comment]
@SammyK you know this is a BC break in fact? ;)

**Comment by SammyK** [comment]
Yes, for those who are using the default fall-back version of Graph. That's why I wanted the next version of the SDK to throw an exception if you don't provide a default Graph version. But in the docs all the examples have the Graph version in the options array so for the copy-pasters, they'll have their Graph version set.

So yeah, it's BC for a very small subset, but I feel like we decided to keep bumping the Graph version every time a new one came out. But I'm cool with just keeping v2.5 for the default fallback in `Facebook` and just updating the docs to v2.6. Then the developers who are using the fall-back option will get upgraded to the next version of Graph when v2.5 is force-upgraded on April 12, 2018.

What do you guys think?

**Comment by yguedidi** [comment]
> That's why I wanted the next version of the SDK to throw an exception if you don't provide a default Graph version.

Me too!

> I feel like we decided to keep bumping the Graph version every time a new one came out.

You're right, I'm not really against this change as we used to do it in the 5.x major version. I said it more like a reminder for 6.x

**Comment by gfosco** [comment]
@SammyK @yguedidi You're now core collaborators with write privileges.  Wield your powers responsibly and for great justice.  🎉

**Comment by SammyK** [comment]
You the man @gfosco! :)

**Pull request merged**
