### PR TITLE
added .gitattributes

### PR DESCRIPTION
**Pull request by EmanueleMinotto**
Closes https://github.com/facebook/facebook-php-sdk-v4/issues/507

This change is more related to Composer than the library itself, should I add something to the `docs` directory anyway?

### CODE REVIEW

**Comment by SammyK** [comment]
I noticed you didn't ignore CHANGELOG.md, CONTRIBUTING.md & README.md. Do you think those should be ignored as well?

**Comment by EmanueleMinotto** [comment]
you're right, this should be production only files + license

**Comment by gfosco** [comment]
:+1: Welcome to the team @EmanueleMinotto !

**Comment by EmanueleMinotto** [comment]
Thanks @gfosco! my pleasure :D

**Pull request merged**
