### PR TITLE
Added PSR2 check to Travis CI

### PR DESCRIPTION
**Pull request by EmanueleMinotto**
Adds the PSR2 check using travis-ci and phpcs.

A [php-cs-fixer](http://cs.sensiolabs.org/) configuration could also be added to speed up the PSR alignment, should I add it to this PR?

### CODE REVIEW

**Comment by yguedidi** [comment]
As you can see, tests fails. Please use the command from CONTRIBUTING.md

**Comment by yguedidi** [comment]
PR is now OK :+1: 

Note: I usually use scrutinizer-ci or style-ci for coding standard things, but this is just my opinion, I'm not against this PR :)

**Comment by EmanueleMinotto** [comment]
I usually don't use scrutinizer-ci to check the coding style, but I agree about the usage of style-ci :)

**Comment by SammyK** [comment]
I don't really care how we check it as long as we're checking it. :)

**Comment by gfosco** [comment]
:+1:

**Pull request merged**
