### PR TITLE
Add PHP CodeSniffer and CONTRIBUTION instructions

### PR DESCRIPTION
**Pull request by SammyK**
Hey @gfosco! In preparation for [Chi PHP UG's open source workshop](http://www.meetup.com/Chicago-PHP-User-Group/events/219902483/) tomorrow, I've added the Code Sniffer dev dependency as a way to check files for PSR-2 before committing them. And I added some more instructions to the CONTRIBUTING file. :)

PS: I'm working hard on the docs as well. I'm about 50% done. :)

### CODE REVIEW

**Comment by yguedidi** [comment]
I personally prefer using scrutinizer-ci for coding style and code analysis.
@SammyK Do you try it? :)

**Comment by SammyK** [comment]
Yeah, that's cool! But I just need a quick way for people to check their code tomorrow night before committing it. We can migrate to scrutinizer-ci whenever we like. :)

**Comment by yguedidi** [comment]
Yes of course! But I don't think PHPCS sould be included in the SDK

**Comment by SammyK** [comment]
Yeah, I feel you. If @gfosco approves #342 and sets it up, I'll resubmit this PR with instructions on how to install scrutinizer globally in the `CONTRIBUTING.md` file.

**Comment by yguedidi** [comment]
It's not necessary to have scrutinizer locally. Like Travis-CI, Scrutinizer-CI will inspect each PR.
@gfosco just need to enable a global config :)

**Comment by SammyK** [comment]
Sorry - it was late when I responded. Lol.

I meant if #342 gets set up, I'll refactor this PR. I'll add instructions to the `CONTRIBUTING.md` on how to install code sniffer globally so you can run a PSR-2 check before submitting a PR and remove the code sniffer dev dependency from the `composer.json`. :)

**Comment by yguedidi** [comment]
Aaaaah OK! :+1:

**Comment by gfosco** [comment]
Since Scrutinizer was added, looks like this is back in your court @SammyK

**Comment by SammyK** [comment]
Finishing up some examples and I'll be posting a doc PR maybe by tomorrow. :)

**Comment by SammyK** [comment]
Removed Code Sniffer dependency. Updated README with Scrutinizer badge. :)

**Pull request merged**
