### PR TITLE
Update README.md, correctly reference Facebook Class

### PR DESCRIPTION
**Pull request by paddyohanlon**
Change `new Facebook\Facebook` to `new Facebook` to fix error 'Fatal error: Class 'Facebook\Facebook\Facebook' not found...'.

### CODE REVIEW

**Comment by paddyohanlon** [comment]
Just signed up

On 9 May 2016 at 20:49, Facebook Community Bot <notifications@github.com>
wrote:

> Thank you for your pull request and welcome to our community. We require
> contributors to sign our Contributor License Agreement, and we don't seem
> to have you on file. In order for us to review and merge your code, please
> sign up at https://code.facebook.com/cla - and if you have received this
> in error or have any questions, please drop us a line at cla@fb.com.
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/facebook-php-sdk-v4/pull/581#issuecomment-217953965>
>



-- 
LinkedIn <http://ie.linkedin.com/pub/paddy-o-hanlon/26/639/b4a> | Twitter
<https://twitter.com/#!/paddy>  | Facebook
<http://www.facebook.com/pages/LOGO-24/196175887081287> | Thoughts and
Travel <http://paddyohanlon.wordpress.com/>
<http://facebook.com/people/Paddy-O-Hanlon/515827544>

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by paddyohanlon** [comment]
Just realised the error I get probably depends in how the Facebook Class is aliased.

**Comment by yguedidi** [comment]
@paddyohanlon Thank you for your contribution!
I think the right fix should be:
```php
// add a leading backslash
$fb = new \Facebook\Facebook([
    // ...
]);

// or add a use statement
use Facebook\Facebook;

$fb = new Facebook([
    // ...
]);
```

ping @SammyK, my vote goes for the use statement :)

**Comment by SammyK** [comment]
Hey @paddyohanlon! This can be alleviated by prepending a backslash `\` to the qualified class name. See [the PHP docs](http://php.net/manual/en/language.namespaces.rules.php) for more details. If you update your PR to include the fully qualified class name, then we can merge it in. :)

**Comment by SammyK** [comment]
Or use the `use` statement like @yguedidi said. Lol. :)

**Comment by paddyohanlon** [comment]
Ok, thanks! Looks like the use statement wins and no need any changes.

On 9 May 2016 at 21:29, Sammy Kaye Powers <notifications@github.com> wrote:

> Or use the use statement like @yguedidi <https://github.com/yguedidi>
> said. Lol. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/facebook-php-sdk-v4/pull/581#issuecomment-217964494>
>



-- 
LinkedIn <http://ie.linkedin.com/pub/paddy-o-hanlon/26/639/b4a> | Twitter
<https://twitter.com/#!/paddy>  | Facebook
<http://www.facebook.com/pages/LOGO-24/196175887081287> | Thoughts and
Travel <http://paddyohanlon.wordpress.com/>
<http://facebook.com/people/Paddy-O-Hanlon/515827544>

**Comment by SammyK** [comment]
@paddyohanlon If you're going to remove the `Facebook\` namespace, you'll need to add `use Facebook\Facebook;` to the top of the example. :)

**Comment by paddyohanlon** [comment]
Got it, thanks!

On 10 May 2016 at 21:31, Sammy Kaye Powers <notifications@github.com> wrote:

> @paddyohanlon <https://github.com/paddyohanlon> If you're going to remove
> the Facebook\ namespace, you'll need to add use Facebook\Facebook; to the
> top of the example. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/facebook-php-sdk-v4/pull/581#issuecomment-218265108>
>



-- 
LinkedIn <http://ie.linkedin.com/pub/paddy-o-hanlon/26/639/b4a> | Twitter
<https://twitter.com/#!/paddy>  | Facebook
<http://www.facebook.com/pages/LOGO-24/196175887081287> | Thoughts and
Travel <http://paddyohanlon.wordpress.com/>
<http://facebook.com/people/Paddy-O-Hanlon/515827544>

**Comment by SammyK** [comment]
Hey @paddyohanlon! Once you update this PR I'll merge. :)

**Comment by SammyK** [comment]
I'm going to go head and finish this one off for you. :)

**Pull request merged**
