### PR TITLE
Add a final class holding all permissions

### PR DESCRIPTION
**Pull request by 0x46616c6b**
For the comfort a final class holding all permissions as a constant for easier usage.

### CODE REVIEW

**Comment by yguedidi** [comment]
Can be useful, but it should go to `master` :)

**Comment by 0x46616c6b** [comment]
What is the plan with the 4.0.* versions? It would be great when I can use the constants with the next minor update. I can additionally create a PR for the master.

**Comment by yguedidi** [comment]
ping @gfosco

**Comment by 0x46616c6b** [comment]
@txptr where is the permission documentated?

**Comment by SammyK** [comment]
There's also a [new `user_posts` permission](https://developers.facebook.com/docs/apps/changelog#v2_3) in v2.3.

**Comment by SammyK** [comment]
And the [`publish_pages` docs are here](https://developers.facebook.com/docs/facebook-login/permissions/v2.3#reference-publish_pages).

**Comment by 0x46616c6b** [comment]
Bleeding edge ;-) I will add it.

**Comment by gfosco** [comment]
Ok.. I'll accept this and tag a point release of 4.0.x.  Consider sending in a PR against Master as well.  Thanks.

**Comment by gfosco** [comment]
4.0.21 tagged with this.

**Pull request merged**
