### PR TITLE
Fix autoload prefix

### PR DESCRIPTION
**Pull request by niraj-shah**
For those that don't use composer...

### CODE REVIEW

**Comment by SammyK** [comment]
What is this fixing exactly? I have no issues using the autoloader on my systems. :)

**Comment by niraj-shah** [comment]
The extra / is breaking the strncmp check - at least in my version when manually including the autoload.php file (as opposed to using composer).

**Comment by SammyK** [comment]
Ah, I see it was [recent commit](https://github.com/facebook/facebook-php-sdk-v4/commit/61e3dba6a3aae5638883dec77cf8dd493d9d4fb9#diff-5f83a4a143986701c77764e45a29c28b) that added the preceding `\` that's messing it all up.

You'll have to fix the conflicts though before it can be merged in.

**Comment by niraj-shah** [comment]
Conflicts resolved.

**Comment by yguedidi** [comment]
You should rebase your branch on master

**Comment by SammyK** [comment]
I agree with @yguedidi - deleting one character shouldn't result in a PR that has 137 files changed with 35 commits. :)

**Comment by yguedidi** [comment]
@SammyK adding one character (2 spaces addition and 1 backslash deletion, +2-1 = +1 ) :p

**Comment by SammyK** [comment]
Oh, you! :)

**Comment by yguedidi** [comment]
After code review, now it's time for comments review ! ;)

**Comment by SammyK** [comment]
I feel like you are my personal life editor. It's kinda nice!

**Comment by yguedidi** [comment]
Haha, I'm honored

**Pull request closed without merging**
