### PR TITLE
Updated copyright year from 2014 to 2016.

### PR DESCRIPTION
**Pull request by jfreed**

### CODE REVIEW

**Comment by SammyK** [comment]
:+1: :D

**Comment by jfreed** [comment]
Sent an email, I don't know why I wouldn't be on file as I signed the CLA moments before submitting the pull request.

**Comment by yguedidi** [comment]
@jfreed you missed the LICENSE file :)
About the CLA, maybe you signed it with a different email than the one you use with git?

**Comment by jfreed** [comment]
File mask replace in PHPStorm strikes again! I fixed that and found tests/FacebookTestCredentials.php.dist as well.

I just double checked and my email is the same with the one I used to sign the CLA.

**Pull request merged**
